test_that("seed resets RNG deterministically", {
  rng <- randompack_rng("pcg64")
  rng$seed(123)
  a <- rng$unif(5)
  rng$seed(123)
  b <- rng$unif(5)
  expect_identical(a, b)
})

test_that("randomize runs and allows draws", {
  rng <- randompack_rng("pcg64")
  rng$randomize()
  x <- rng$unif(5)
  expect_type(x, "double")
  expect_length(x, 5)
  expect_true(all(is.finite(x)))
})

test_that("set_state accepts numeric state words", {
  rng1 <- randompack_rng("pcg64")
  rng2 <- randompack_rng("pcg64")
  state <- c(1, 0, 2, 0, 3, 0, 4, 0)
  rng1$set_state(state)
  rng2$set_state(state)
  expect_identical(rng1$unif(5), rng2$unif(5))
})

test_that("pcg64_set_inc makes draws repeatable", {
  rng1 <- randompack_rng("pcg64")
  rng2 <- randompack_rng("pcg64")
  state <- c(1, 0, 2, 0, 1, 0, 0, 0)
  inc <- c(3, 0, 5, 0)
  rng1$set_state(state)
  rng2$set_state(state)
  rng1$pcg64_set_inc(inc)
  rng2$pcg64_set_inc(inc)
  expect_identical(rng1$unif(5), rng2$unif(5))
  expect_error(rng1$pcg64_set_inc(c(2, 0, 5, 0)))
})

test_that("sfc64_set_abc makes draws repeatable", {
  rng1 <- randompack_rng("sfc64")
  rng2 <- randompack_rng("sfc64")
  abc <- c(7, 0, 11, 0, 13, 0)
  rng1$set_state(c(1, 0, 2, 0, 3, 0, 17, 0))
  rng2$set_state(c(1, 0, 2, 0, 3, 0, 17, 0))
  rng1$sfc64_set_abc(abc)
  rng2$sfc64_set_abc(abc)
  expect_identical(rng1$unif(5), rng2$unif(5))
})

test_that("philox setters make draws repeatable", {
  rng1 <- randompack_rng("philox")
  rng2 <- randompack_rng("philox")
  counter <- c(1, 0, 2, 0, 3, 0, 4, 0)
  key <- c(5, 0, 6, 0)
  rng1$philox_set_ctr(counter)
  rng1$philox_set_key(key)
  rng2$philox_set_ctr(counter)
  rng2$philox_set_key(key)
  expect_identical(rng1$unif(5), rng2$unif(5))
})

test_that("squares setters make draws repeatable", {
  rng1 <- randompack_rng("squares")
  rng2 <- randompack_rng("squares")
  counter <- c(1, 0)
  key <- c(2, 0)
  rng1$squares_set_ctr(counter)
  rng1$squares_set_key(key)
  rng2$squares_set_ctr(counter)
  rng2$squares_set_key(key)
  expect_identical(rng1$unif(5), rng2$unif(5))
})

test_that("jump advances the default engine", {
  rng1 <- randompack_rng()
  rng2 <- randompack_rng()
  rng1$seed(123)
  rng2$seed(123)
  a <- rng1$unif(5)
  rng2$jump(128)
  b <- rng2$unif(5)
  expect_false(identical(a, b))
  expect_error(rng1$jump(129))
  expect_error(rng1$jump(254))
})
