name: Linux-wheels

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CIBW_ARCHS_LINUX: "x86_64"
      CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp314-*"
      CIBW_CONFIG_SETTINGS: "setup-args=-Dblas=builtin"
      
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: python -m pip install -U pip cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel python/

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: wheelhouse/*.whl
          retention-days: 7
